baseURL = "https://ec2spotworkshops.com/"
languageCode = "en-us"
title = "EC2 Spot Workshops"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
googleAnalytics = "UA-136840914-1"


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = true
description = "EC2 Spot Workshops"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = false
disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false


[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Amazon EC2 Spot Instances"
url = "https://aws.amazon.com/ec2/spot/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Feedback / Questions?"
url = "mailto:ec2-spot-workshops@amazon.com"
weight = 30
